version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - demo1
      - demo2
      - demo3
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: claveSQL1253
      MYSQL_DATABASE: tingeso1
    ports:
      - 33060:3306
  demo1:
    container_name: demo1
    image: josetorob/tingeso
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tingeso1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=claveSQL1253
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
  demo2:
    container_name: demo2
    image: josetorob/tingeso
    ports:
      - "8092:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tingeso1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=claveSQL1253
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
  demo3:
    container_name: demo3
    image: josetorob/tingeso
    ports:
      - "8093:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tingeso1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=claveSQL1253
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db